source = $HOME/.cache/wal/colors-hyprland.conf

background {
	monitor =
	path = $wallpaper
	blur_size = 2
	blur_passes = 2
}

input-field {
	monitor = 
	size = 150, 50
	outline_thickness = 0
	dots_rounding = 4 
	dots_spacing = .5
	inner_color = $background
	outer_color = $background
	check_color = $background
	font_color = $color9
	fade_on_empty = false
	shadow_color = $color9	
	shadow_passes = 2
	shadow_size = 2
	rounding = 10
	placeholder_text = <i></i>
	fail_text = <b>IDIOT</b>
	position = 0, -300
	halign = center
	valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%I</b>"
    color = $color9
    font_size = 200
    position = -120, 310
    halign = center
    valign = center
}


label {
    monitor =
    text = cmd[update:1000] date +"<b>%M</b>"
    color = $color7
	font_size = 200
    shadow_passes = 0
    shadow_size = 5
    position = 120, 130
    halign = center
    valign = center
}
