################
### MONITORS ###
################

monitor = eDP-1, preferred, auto, 1.2

####################
### STARTUP APPS ###
####################

exec-once = [workspace 1 silent] xdg-open https://trello.com/b/CaA3cNLS/school
exec-once = [workspace 2 silent] spotify
exec-once = [workspace 3 silent] xdg-open https://rcas.instructure.com/login/ldap
