################
### MONITORS ###
################

monitor = eDP-1, preferred, auto, 1.2

####################
### STARTUP APPS ###
####################

exec-once = [workspace 1 silent] firefox --new-window https://trello.com/b/CaA3cNLS/school
exec-once = [workspace 2 silent] spotify
exec-once = [workspace 3 silent] sleep 3 && firefox --new-window https://rcas.instructure.com/login/ldap

windowrule = workspace 1, match:class firefox, match:title .*[Tt]rello.*
windowrule = workspace 3, match:class firefox, match:title .*(Canvas|[Ii]nstructure).*

#############
### INPUT ###
#############

input {
    sensitivity = 0
}
